### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by cetra3** [philipmeadows/alfresco-webscript-manifold-connector#10]
When running ManifoldCF in Tomcat, with the Alfresco Webscripts connector as a repository connector, the following exception repeats within the log upon job execution:

```
java.lang.IllegalAccessError: tried to access field org.apache.manifoldcf.crawler.system.SeedingActivity.jobID from class org.apache.manifoldcf.crawler.system.JobIdStealer
at org.apache.manifoldcf.crawler.system.JobIdStealer.stealId(JobIdStealer.java:18)
at org.apache.manifoldcf.crawler.system.JobIdStealer.stealId(JobIdStealer.java:14)
at org.alfresco.consulting.manifold.AlfrescoConnector.addSeedDocuments(AlfrescoConnector.java:120)
at org.apache.manifoldcf.crawler.connectors.BaseRepositoryConnector.addSeedDocuments(BaseRepositoryConnector.java:156)
at org.apache.manifoldcf.crawler.system.StartupThread.run(StartupThread.java:153)
```

**Comment by maoo** [comment]
Sharing a work-around from @cetra3 

_To work around it, I’ve copied the JobIdStealer.class file into WEB-INF/lib/mcf-pull-agent.jar and it seems like the error has gone away._

The JobIdStealer class should be removed and jobId should be retrieved via Manifold internal APIs.
